version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amaris"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lq1d5vh8covl"
s3_prefix = "amaris"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"dev\""
image_repositories = []
